//! Atlas Core Engine
//! 
//! The declarative foundation of Atlas ERP. This module contains:
//! - Schema engine for dynamic entity definitions
//! - Workflow engine for state machine execution
//! - Validation engine for declarative rules
//! - Formula engine for computed fields
//! - Security engine for access control
//! - Audit engine for change tracking
//! - Configuration engine for hot-reload
//! - Event bus for inter-service communication
//! - Notification engine (Oracle Fusion bell-icon notifications)
//! - Approval engine (Oracle Fusion multi-level approvals)

pub mod schema;
pub mod workflow;
pub mod validation;
pub mod formula;
pub mod security;
pub mod audit;
pub mod config;
pub mod eventbus;
pub mod notification;
pub mod approval;
pub mod period_close;
pub mod currency;
pub mod tax;
pub mod intercompany;
pub mod reconciliation;
pub mod budget;
pub mod expense;
pub mod fixed_assets;
pub mod collections;
pub mod revenue;
pub mod payment;
pub mod subledger_accounting;
pub mod encumbrance;
pub mod cash_management;
pub mod sourcing;
pub mod lease;
pub mod project_costing;
pub mod cost_allocation;
pub mod financial_reporting;
pub mod withholding_tax;
pub mod multi_book;
pub mod procurement_contracts;
pub mod inventory;
pub mod customer_returns;
pub mod pricing;
pub mod sales_commission;
pub mod subscription;
pub mod treasury;
pub mod grant_management;
pub mod corporate_card;
pub mod financial_consolidation;
pub mod supplier_qualification;
pub mod recurring_journal;
pub mod manual_journal;
pub mod document_sequencing;
pub mod descriptive_flexfield;
pub mod cross_validation;
pub mod scheduled_process;
pub mod segregation_of_duties;
pub mod allocation;
pub mod currency_revaluation;
pub mod purchase_requisition;
pub mod benefits;
pub mod autoinvoice;
pub mod performance;
pub mod credit_management;
pub mod product_information;
pub mod quality_management;
pub mod transfer_pricing;
pub mod order_management;
pub mod approval_delegation;
pub mod manufacturing;
pub mod warehouse_management;
pub mod absence;
pub mod time_and_labor;
pub mod approval_authority;
pub mod data_archiving;
pub mod payroll;
pub mod compensation;
pub mod service_request;
pub mod lead_opportunity;
pub mod demand_planning;
pub mod shipping;
pub mod recruiting;
pub mod marketing;
pub mod receiving;
pub mod supplier_scorecard;
pub mod kpi;
pub mod account_monitor;
pub mod goal_management;
pub mod landed_cost;
pub mod contract_lifecycle;
pub mod succession_planning;
pub mod learning_management;
pub mod joint_venture;
pub mod enterprise_asset_management;
pub mod risk_management;
pub mod project_billing;
pub mod engineering_change_management;
pub mod sustainability;
pub mod channel_revenue;
pub mod product_configurator;
pub mod transportation_management;
pub mod territory_management;
pub mod promotions_management;
pub mod cost_accounting;
pub mod accounts_payable;
pub mod supply_chain_planning;
pub mod health_safety;
pub mod funds_reservation;
pub mod rebate_management;
pub mod project_resource_management;
pub mod loyalty_management;
pub mod accounts_receivable;
pub mod general_ledger;
pub mod asset_depreciation;
pub mod netting;
pub mod financial_statements;
pub mod journal_import;
pub mod inflation_adjustment;
pub mod impairment_management;
pub mod bank_account_transfer;
pub mod tax_reporting;
pub mod deferred_revenue;
pub mod accounting_hub;
pub mod financial_controls;
pub mod revenue_management;
pub mod cash_flow_forecast;
pub mod regulatory_reporting;
pub mod advance_payment;
pub mod customer_deposit;
pub mod cash_position;
pub mod payment_terms;
pub mod lockbox;
pub mod ar_aging;
pub mod ap_aging;
pub mod financial_ratio;
pub mod receipt_write_off;
pub mod mass_additions;
pub mod asset_reclassification;
pub mod gl_budget_transfer;
pub mod payment_format;
pub mod financial_dimension_set;
pub mod prepayment_application;
pub mod asset_retirement;
pub mod cip_capitalization;
pub mod available_funds;
pub mod statistical_accounting;
pub mod account_hierarchy;
pub mod suspense_account;
pub mod interest_invoice;
pub mod expense_policy_compliance;
pub mod bank_guarantee;
pub mod letter_of_credit;
pub mod hedge_management;
pub mod payment_risk;
pub mod tax_registration;
pub mod cash_concentration;
pub mod customer_statement;

pub use schema::*;
pub use workflow::{
    WorkflowEngine, StateMachine, GuardEvaluator, GuardResult,
    ActionExecutor, ActionResult,
    WorkflowState, StateHistoryEntry, TransitionResult,
    AvailableTransitions, TransitionInfo,
    repository::{WorkflowStateRepository, PostgresWorkflowStateRepository, InMemoryWorkflowStateRepository},
};

// Re-export the workflow engine's User type under a distinct path
// so downstream crates can import it without colliding with
// atlas_shared::User.
pub use workflow::engine::User as WorkflowUser;

pub use validation::*;
pub use formula::*;
pub use security::*;
pub use audit::*;
pub use config::*;
pub use eventbus::*;
pub use notification::{NotificationEngine, PostgresNotificationRepository as PostgresNotificationRepo};
pub use approval::{ApprovalEngine, PostgresApprovalRepository as PostgresApprovalRepo};
pub use period_close::{PeriodCloseEngine, PostgresPeriodCloseRepository as PostgresPeriodCloseRepo};
pub use currency::{CurrencyEngine, PostgresCurrencyRepository as PostgresCurrencyRepo};
pub use tax::{TaxEngine, PostgresTaxRepository as PostgresTaxRepo};
pub use intercompany::{IntercompanyEngine, PostgresIntercompanyRepository as PostgresIntercompanyRepo};
pub use reconciliation::{ReconciliationEngine, PostgresReconciliationRepository as PostgresReconciliationRepo};
pub use expense::{ExpenseEngine, PostgresExpenseRepository as PostgresExpenseRepo};
pub use budget::{BudgetEngine, PostgresBudgetRepository as PostgresBudgetRepo};
pub use fixed_assets::{FixedAssetEngine, PostgresFixedAssetRepository as PostgresFixedAssetRepo};
pub use collections::{CollectionsEngine, PostgresCollectionsRepository as PostgresCollectionsRepo};
pub use revenue::{RevenueEngine, PostgresRevenueRepository as PostgresRevenueRepo};
pub use payment::{PaymentEngine, PostgresPaymentRepository as PostgresPaymentRepo};
pub use subledger_accounting::{SubledgerAccountingEngine, PostgresSubledgerAccountingRepository as PostgresSubledgerAccountingRepo};
pub use encumbrance::{EncumbranceEngine, PostgresEncumbranceRepository as PostgresEncumbranceRepo};
pub use cash_management::{CashManagementEngine, PostgresCashManagementRepository as PostgresCashManagementRepo};
pub use sourcing::{SourcingEngine, PostgresSourcingRepository as PostgresSourcingRepo};
pub use lease::{LeaseAccountingEngine, PostgresLeaseAccountingRepository as PostgresLeaseAccountingRepo};
pub use project_costing::{ProjectCostingEngine, PostgresProjectCostingRepository as PostgresProjectCostingRepo};
pub use cost_allocation::{CostAllocationEngine, PostgresCostAllocationRepository as PostgresCostAllocationRepo};
pub use financial_reporting::{FinancialReportingEngine, PostgresFinancialReportingRepository as PostgresFinancialReportingRepo};
pub use withholding_tax::{WithholdingTaxEngine, PostgresWithholdingTaxRepository as PostgresWithholdingTaxRepo};
pub use multi_book::{MultiBookAccountingEngine, PostgresMultiBookAccountingRepository as PostgresMultiBookAccountingRepo};
pub use procurement_contracts::{ProcurementContractEngine, PostgresProcurementContractRepository as PostgresProcurementContractRepo};
pub use inventory::{InventoryEngine, PostgresInventoryRepository as PostgresInventoryRepo};
pub use customer_returns::{CustomerReturnsEngine, PostgresCustomerReturnsRepository as PostgresCustomerReturnsRepo};
pub use pricing::{PricingEngine, PostgresPricingRepository as PostgresPricingRepo};
pub use sales_commission::{SalesCommissionEngine, PostgresSalesCommissionRepository as PostgresSalesCommissionRepo};
pub use treasury::{TreasuryEngine, PostgresTreasuryRepository as PostgresTreasuryRepo};
pub use subscription::{SubscriptionEngine, PostgresSubscriptionRepository as PostgresSubscriptionRepo};
pub use grant_management::{GrantManagementEngine, PostgresGrantManagementRepository as PostgresGrantManagementRepo};
pub use corporate_card::{CorporateCardEngine, PostgresCorporateCardRepository as PostgresCorporateCardRepo};
pub use financial_consolidation::{FinancialConsolidationEngine, PostgresFinancialConsolidationRepository as PostgresFinancialConsolidationRepo};
pub use supplier_qualification::{SupplierQualificationEngine, PostgresSupplierQualificationRepository as PostgresSupplierQualificationRepo};
pub use recurring_journal::{RecurringJournalEngine, PostgresRecurringJournalRepository as PostgresRecurringJournalRepo};
pub use manual_journal::{ManualJournalEngine, PostgresManualJournalRepository as PostgresManualJournalRepo};
pub use document_sequencing::{DocumentSequencingEngine, PostgresDocumentSequencingRepository as PostgresDocumentSequencingRepo};
pub use descriptive_flexfield::{DescriptiveFlexfieldEngine, PostgresDescriptiveFlexfieldRepository as PostgresDescriptiveFlexfieldRepo};
pub use cross_validation::{CrossValidationEngine, PostgresCrossValidationRepository as PostgresCrossValidationRepo};
pub use scheduled_process::{ScheduledProcessEngine, PostgresScheduledProcessRepository as PostgresScheduledProcessRepo};
pub use segregation_of_duties::{SegregationOfDutiesEngine, PostgresSegregationOfDutiesRepository as PostgresSegregationOfDutiesRepo};
pub use allocation::{AllocationEngine, PostgresAllocationRepository as PostgresAllocationRepo};
pub use currency_revaluation::{CurrencyRevaluationEngine, PostgresCurrencyRevaluationRepository as PostgresCurrencyRevaluationRepo};
pub use purchase_requisition::{PurchaseRequisitionEngine, PostgresPurchaseRequisitionRepository as PostgresPurchaseRequisitionRepo};
pub use benefits::{BenefitsEngine, PostgresBenefitsRepository as PostgresBenefitsRepo};
pub use autoinvoice::{AutoInvoiceEngine, PostgresAutoInvoiceRepository as PostgresAutoInvoiceRepo};
pub use performance::{PerformanceEngine, PostgresPerformanceRepository as PostgresPerformanceRepo};
pub use credit_management::{CreditManagementEngine, PostgresCreditManagementRepository as PostgresCreditManagementRepo};
pub use product_information::{ProductInformationEngine, PostgresProductInformationRepository as PostgresProductInformationRepo};
pub use quality_management::{QualityManagementEngine, PostgresQualityManagementRepository as PostgresQualityManagementRepo};
pub use transfer_pricing::{TransferPricingEngine, PostgresTransferPricingRepository as PostgresTransferPricingRepo};
pub use order_management::{OrderManagementEngine, PostgresOrderManagementRepository as PostgresOrderManagementRepo};
pub use approval_delegation::{ApprovalDelegationEngine, PostgresApprovalDelegationRepository as PostgresApprovalDelegationRepo};
pub use manufacturing::{ManufacturingEngine, PostgresManufacturingRepository as PostgresManufacturingRepo};
pub use warehouse_management::{WarehouseManagementEngine, PostgresWarehouseManagementRepository as PostgresWarehouseManagementRepo};
pub use absence::{AbsenceEngine, PostgresAbsenceRepository as PostgresAbsenceRepo};
pub use time_and_labor::{TimeAndLaborEngine, PostgresTimeAndLaborRepository as PostgresTimeAndLaborRepo};
pub use approval_authority::{ApprovalAuthorityEngine, PostgresApprovalAuthorityRepository as PostgresApprovalAuthorityRepo};
pub use data_archiving::{DataArchivingEngine, PostgresDataArchivingRepository as PostgresDataArchivingRepo};
pub use payroll::{PayrollEngine, PostgresPayrollRepository as PostgresPayrollRepo};
pub use compensation::{CompensationEngine, PostgresCompensationRepository as PostgresCompensationRepository};
pub use service_request::{ServiceRequestEngine, PostgresServiceRequestRepository as PostgresServiceRequestRepo};
pub use lead_opportunity::{LeadOpportunityEngine, PostgresLeadOpportunityRepository as PostgresLeadOpportunityRepo};
pub use demand_planning::{DemandPlanningEngine, PostgresDemandPlanningRepository as PostgresDemandPlanningRepo};
pub use shipping::{ShippingEngine, PostgresShippingRepository as PostgresShippingRepo};
pub use recruiting::{RecruitingEngine, PostgresRecruitingRepository as PostgresRecruitingRepo};
pub use marketing::{MarketingEngine, PostgresMarketingRepository as PostgresMarketingRepo};
pub use receiving::{ReceivingEngine, PostgresReceivingRepository as PostgresReceivingRepo};
pub use supplier_scorecard::{SupplierScorecardEngine, PostgresScorecardRepository as PostgresScorecardRepo};
pub use kpi::{KpiEngine, PostgresKpiRepository as PostgresKpiRepo};
pub use account_monitor::{AccountMonitorEngine, PostgresAccountMonitorRepository as PostgresAccountMonitorRepo};
pub use goal_management::{GoalManagementEngine, PostgresGoalManagementRepository as PostgresGoalManagementRepo};
pub use landed_cost::{LandedCostEngine, PostgresLandedCostRepository as PostgresLandedCostRepo};
pub use contract_lifecycle::{ContractLifecycleEngine, PostgresContractLifecycleRepository as PostgresContractLifecycleRepo};
pub use succession_planning::{SuccessionPlanningEngine, PostgresSuccessionPlanningRepository as PostgresSuccessionPlanningRepo};
pub use learning_management::{LearningManagementEngine, PostgresLearningManagementRepository as PostgresLearningManagementRepo};
pub use joint_venture::{JointVentureEngine, PostgresJointVentureRepository as PostgresJointVentureRepo};
pub use risk_management::{RiskManagementEngine, PostgresRiskManagementRepository as PostgresRiskManagementRepo};
pub use enterprise_asset_management::{EnterpriseAssetManagementEngine, PostgresAssetManagementRepository as PostgresAssetManagementRepo};
pub use project_billing::{ProjectBillingEngine, PostgresProjectBillingRepository as PostgresProjectBillingRepo};
pub use sustainability::{SustainabilityEngine, PostgresSustainabilityRepository as PostgresSustainabilityRepo};
pub use engineering_change_management::{EngineeringChangeEngine, PostgresEngineeringChangeManagementRepository as PostgresEcmRepository};
pub use channel_revenue::{ChannelRevenueEngine, PostgresChannelRevenueRepository as PostgresChannelRevenueRepo};
pub use product_configurator::{ProductConfiguratorEngine, PostgresProductConfiguratorRepository as PostgresProductConfiguratorRepo};
pub use transportation_management::{TransportationManagementEngine, PostgresTransportationManagementRepository as PostgresTransportationManagementRepo};
pub use territory_management::{TerritoryManagementEngine, PostgresTerritoryManagementRepository as PostgresTerritoryManagementRepo};
pub use promotions_management::{PromotionsManagementEngine, PostgresPromotionsManagementRepository as PostgresPromotionsManagementRepo};
pub use cost_accounting::{CostAccountingEngine, PostgresCostAccountingRepository as PostgresCostAccountingRepo};
pub use accounts_payable::{AccountsPayableEngine, PostgresAccountsPayableRepository as PostgresAccountsPayableRepo};
pub use supply_chain_planning::{SupplyChainPlanningEngine, PostgresPlanningRepository as PostgresPlanningRepo};
pub use health_safety::{HealthSafetyEngine, PostgresHealthSafetyRepository as PostgresHealthSafetyRepo};
pub use funds_reservation::{FundsReservationEngine, PostgresFundsReservationRepository as PostgresFundsReservationRepo};
pub use rebate_management::{RebateManagementEngine, PostgresRebateManagementRepository as PostgresRebateManagementRepo};
pub use project_resource_management::{ProjectResourceManagementEngine, PostgresProjectResourceManagementRepository as PostgresProjectResourceManagementRepo};
pub use loyalty_management::{LoyaltyManagementEngine, PostgresLoyaltyManagementRepository as PostgresLoyaltyManagementRepo};
pub use accounts_receivable::{AccountsReceivableEngine, PostgresAccountsReceivableRepository as PostgresAccountsReceivableRepo};
pub use general_ledger::{GeneralLedgerEngine, PostgresGeneralLedgerRepository as PostgresGeneralLedgerRepo};
pub use asset_depreciation::{AssetDepreciationEngine, PostgresAssetDepreciationRepository as PostgresAssetDepreciationRepo};
pub use netting::{NettingEngine, PostgresNettingRepository as PostgresNettingRepo};
pub use financial_statements::{FinancialStatementEngine, PostgresFinancialStatementRepository as PostgresFinancialStatementRepo};
pub use journal_import::{JournalImportEngine, PostgresJournalImportRepository as PostgresJournalImportRepo};
pub use inflation_adjustment::{InflationAdjustmentEngine, PostgresInflationAdjustmentRepository as PostgresInflationAdjustmentRepo};
pub use impairment_management::{ImpairmentManagementEngine, PostgresImpairmentManagementRepository as PostgresImpairmentManagementRepo};
pub use bank_account_transfer::{BankAccountTransferEngine, PostgresBankAccountTransferRepository as PostgresBankAccountTransferRepo};
pub use tax_reporting::{TaxReportingEngine, PostgresTaxReportingRepository as PostgresTaxReportingRepo};
pub use deferred_revenue::{DeferredRevenueEngine, PostgresDeferredRevenueRepository as PostgresDeferredRevenueRepo};
pub use accounting_hub::{AccountingHubEngine, PostgresAccountingHubRepository as PostgresAccountingHubRepo};
pub use financial_controls::{FinancialControlsEngine, PostgresFinancialControlsRepository as PostgresFinancialControlsRepo};
pub use revenue_management::RevenueManagementEngine;
pub use cash_flow_forecast::CashFlowForecastEngine;
pub use regulatory_reporting::RegulatoryReportingEngine;
pub use advance_payment::{AdvancePaymentEngine, PostgresAdvancePaymentRepository as PostgresAdvancePaymentRepo};
pub use customer_deposit::{CustomerDepositEngine, PostgresCustomerDepositRepository as PostgresCustomerDepositRepo};
pub use cash_position::{CashPositionEngine, PostgresCashPositionRepository as PostgresCashPositionRepo};
pub use payment_terms::{PaymentTermsEngine, PostgresPaymentTermsRepository as PostgresPaymentTermsRepo};
pub use lockbox::{LockboxEngine, PostgresLockboxRepository as PostgresLockboxRepo};
pub use ar_aging::{ArAgingEngine, PostgresArAgingRepository as PostgresArAgingRepo};
pub use ap_aging::{ApAgingEngine, PostgresApAgingRepository as PostgresApAgingRepo};
pub use financial_ratio::{FinancialRatioEngine, PostgresFinancialRatioRepository as PostgresFinancialRatioRepo};
pub use receipt_write_off::{ReceiptWriteOffEngine, PostgresReceiptWriteOffRepository as PostgresReceiptWriteOffRepo};
pub use mass_additions::{MassAdditionEngine, PostgresMassAdditionRepository as PostgresMassAdditionRepo};
pub use asset_reclassification::{AssetReclassificationEngine, PostgresAssetReclassificationRepository as PostgresAssetReclassificationRepo};
pub use gl_budget_transfer::{GlBudgetTransferEngine, PostgresGlBudgetTransferRepository as PostgresGlBudgetTransferRepo};
pub use payment_format::{PaymentFormatEngine, PostgresPaymentFormatRepository as PostgresPaymentFormatRepo};
pub use financial_dimension_set::{FinancialDimensionSetEngine, PostgresFinancialDimensionSetRepository as PostgresFinancialDimensionSetRepo};
pub use prepayment_application::{PrepaymentApplicationEngine, PostgresPrepaymentApplicationRepository as PostgresPrepaymentApplicationRepo};
pub use asset_retirement::{AssetRetirementEngine, PostgresAssetRetirementRepository as PostgresAssetRetirementRepo};
pub use cip_capitalization::{CipCapitalizationEngine, PostgresCipCapitalizationRepository as PostgresCipCapitalizationRepo};
pub use available_funds::{AvailableFundsEngine, PostgresAvailableFundsRepository as PostgresAvailableFundsRepo};
pub use statistical_accounting::{StatisticalAccountingEngine, PostgresStatisticalAccountingRepository as PostgresStatisticalAccountingRepo};
pub use account_hierarchy::{AccountHierarchyEngine, PostgresAccountHierarchyRepository as PostgresAccountHierarchyRepo};
pub use suspense_account::{SuspenseAccountEngine, PostgresSuspenseAccountRepository as PostgresSuspenseAccountRepo};
pub use interest_invoice::{InterestInvoiceEngine, PostgresInterestInvoiceRepository as PostgresInterestInvoiceRepo};
pub use expense_policy_compliance::{ExpensePolicyComplianceEngine, PostgresExpensePolicyComplianceRepository as PostgresExpensePolicyComplianceRepo};
pub use bank_guarantee::{BankGuaranteeEngine, PostgresBankGuaranteeRepository as PostgresBankGuaranteeRepo};
pub use letter_of_credit::{LetterOfCreditEngine, PostgresLetterOfCreditRepository as PostgresLetterOfCreditRepo};
pub use hedge_management::{HedgeManagementEngine, repository::PostgresHedgeManagementRepository as PostgresHedgeManagementRepo};
pub use payment_risk::{PaymentRiskEngine, repository::PostgresPaymentRiskRepository as PostgresPaymentRiskRepo};
pub use tax_registration::{TaxRegistrationEngine, PostgresTaxRegistrationRepository as PostgresTaxRegistrationRepo};
pub use cash_concentration::{CashConcentrationEngine, PostgresCashConcentrationRepository as PostgresCashConcentrationRepo};
pub use customer_statement::{CustomerStatementEngine, PostgresCustomerStatementRepository as PostgresCustomerStatementRepo};

mod mock_repos;
pub use mock_repos::*;
