//! E2E test modules

mod common;

mod auth;
mod crud;
mod workflow;
mod schema;
mod admin;
mod report;

mod procure_to_pay;
mod order_to_cash;
mod period_close;
mod currency;
mod tax;
mod reconciliation;
mod expense;
mod budget;
mod fixed_assets;
mod encumbrance;
mod cash_management;
mod sourcing;
mod lease;
mod project_costing;
mod cost_allocation;
mod financial_reporting;
mod multi_book;
mod procurement_contracts;
mod inventory;
mod customer_returns;
mod pricing;
mod sales_commission;
mod treasury;
mod grant_management;
mod supplier_qualification;
mod recurring_journal;
mod manual_journal;
mod descriptive_flexfield;
mod cross_validation;
mod scheduled_process;
mod segregation_of_duties;
mod allocation;
mod currency_revaluation;
mod corporate_card;
mod benefits;
mod performance;
mod credit_management;
mod product_information;
