//! Atlas Financials
//! 
//! Provides financial management modules inspired by Oracle Fusion Cloud ERP:
//! - General Ledger (Chart of Accounts, Journal Entries)
//! - Accounts Payable (AP Invoices, Payments, Holds)
//! - Accounts Receivable (AR Transactions, Receipts, Credit Memos, Adjustments)
//! - Fixed Assets (Categories, Books, Assets, Depreciation, Transfers, Retirements)
//! - Cost Management (Cost Books, Elements, Profiles, Standard Costs, Adjustments, Variances)
//! - Budgeting & Planning
//! - Expense Reports

pub mod entities;
pub mod services;

pub use services::{
    PurchaseOrderService,
    InvoiceService,
    GeneralLedgerService,
    AccountsPayableService,
    AccountsReceivableService,
    FixedAssetsService,
    CostManagementService,
    RevenueRecognitionService,
    SubledgerAccountingService,
    CashManagementFinService,
    TaxManagementService,
    IntercompanyFinService,
    PeriodCloseFinService,
    LeaseAccountingFinService,
    BankReconciliationService,
    EncumbranceManagementService,
    CurrencyManagementService,
    MultiBookAccountingFinService,
    FinancialConsolidationFinService,
    CollectionsManagementService,
    CreditManagementFinService,
    WithholdingTaxService,
    ProjectBillingService,
    PaymentTermsService,
    FinancialStatementService,
    TaxFilingService,
    JournalReversalService,
    InflationAdjustmentService,
    ImpairmentManagementService,
    BankAccountTransferService,
    TaxReportingService,
    GrantManagementService,
    CorporateCardManagementService,
    TreasuryService,
    RecurringJournalService,
    AutoInvoiceService,
    NettingService,
    SubscriptionService,
    FundsReservationService,
    RebateManagementService,
    ChannelRevenueManagementService,
    FinancialControlsService,
    AccountingHubService,
    DocumentSequencingService,
    CrossValidationRuleService,
    DescriptiveFlexfieldService,
    JointVentureManagementService,
    AdvancePaymentService,
    CustomerDepositService,
    CostAllocationService,
    DepreciationRunService,
    DistributionSetService,
    BudgetOrganizationService,
    InterestInvoiceService,
    PaymentBatchService,
    RevenueBudgetService,
    FinancialDimensionService,
    AutoOffsetService,
    // New Oracle Fusion financial features
    DunningLetterService,
    DunningSummary,
    RevenueWaterfallService,
    WaterfallPeriod,
    WaterfallReport,
    WaterfallLineItem,
    SubledgerReconciliationService,
    ReconciliationResult,
    ReconciliationReport,
    CostRateCardService,
    RateCardEntry,
    // New Oracle Fusion financial features
    LandedCostManagementService,
    CurrencyRevaluationService,
    GLAllocationService,
    CostPoolManagementService,
    WriteOffRequestService,
    LockboxProcessingService,
    LockboxMatchResult,
    LockboxSummary,
    FinancialRatioAnalysisService,
    FinancialStatementData,
    FinancialRatios,
    ReceivableAgingSnapshotService,
    AgingBuckets,
    AgingPercentages,
    AgingTrend,
    // New Oracle Fusion financial features
    MassAdditionService,
    AssetReclassificationService,
    GLBudgetTransferService,
    PaymentFormatService,
    FinancialDimensionSetService,
    ReceiptWriteOffService,
    PrepaymentApplicationService,
    // New Oracle Fusion financial features
    ExpenseReportLineService,
    PaymentProcessRequestService,
    CashPoolingService,
    StatisticalAccountService,
    AssetSplitService,
    AssetMergerService,
    // New Oracle Fusion financial features
    CustomerStatementService,
    AutoCashApplicationService,
    AutoCashMatchResult,
    RevenuePriceProfileService,
    DoubtfulAccountAllowanceService,
    BalanceForwardBillingService,
    AssetCapitalizationService,
    // New Oracle Fusion financial features
    InvoiceToleranceMatchingService,
    MatchResult,
    InvoiceMatchOutcome,
    PaymentMaturityDiscountService,
    PaymentMaturityResult,
    DiscountTier,
    SupplierBankValidationService,
    BankValidationResult,
    AutomaticTaxDeterminationService,
    TaxDeterminationResult,
    TaxRule,
    TransactionPurgeArchiveService,
    ArchiveEligibility,
    ArchiveRunStatistics,
    MultiLevelApprovalService,
    ApprovalLevelDef,
    ApprovalRoutingResult,
    ApprovalAction,
    // New Oracle Fusion financial features
    CashFlowStatementService,
    CashFlowCategory,
    CashFlowLineItem,
    CashFlowStatementResult,
    ReceivableApplicationEngine,
    ApplicationMatchResult,
    AccountingEventProcessor,
    GeneratedJournalLine,
    AccountingEventResult,
    AssetDepreciationScheduleService,
    DepreciationSchedulePeriod,
    // Expense Policy Compliance Engine
    ExpensePolicyComplianceService,
    ExpensePolicyRuleData,
    ExpenseLineData,
    PolicyEvaluationResult,
    ComplianceReport,
    // Bank Guarantee Management
    BankGuaranteeManagementService,
    // Hedge Management
    HedgeManagementService,
    HedgeEffectivenessTestResult,
    HedgeIneffectivenessResult,
    // Payment Risk & Fraud Detection
    PaymentRiskDetectionService,
    DuplicateDetectionResult,
    PaymentRiskScore,
    RiskFactor,
    VelocityCheckResult,
    SanctionsMatch,
};
